/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdvertisingBoard } from "./AdvertisingBoard";
export type { IOpsProxyFactory } from "./IOpsProxyFactory";
