/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AdvertisingBoard__factory } from "./AdvertisingBoard__factory";
export { IOpsProxyFactory__factory } from "./IOpsProxyFactory__factory";
