/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GelatoBlastPoints__factory } from "./GelatoBlastPoints__factory";
export { IBlastPoints__factory } from "./IBlastPoints__factory";
