/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GelatoBlastPoints } from "./GelatoBlastPoints";
export type { IBlastPoints } from "./IBlastPoints";
