/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GelatoVRFConsumerBase } from "./GelatoVRFConsumerBase";
export type { IGelatoVRFConsumer } from "./IGelatoVRFConsumer";
