/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as advertisingBoardSol from "./AdvertisingBoard.sol";
export type { advertisingBoardSol };
export type { CoingeckoOracle } from "./CoingeckoOracle";
