/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAutomate } from "./IAutomate";
export type { IGelato } from "./IGelato";
export type { IGelato1Balance } from "./IGelato1Balance";
export type { IOpsProxyFactory } from "./IOpsProxyFactory";
export type { IProxyModule } from "./IProxyModule";
