/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as advertisingBoardSol from "./AdvertisingBoard.sol";
export { CoingeckoOracle__factory } from "./CoingeckoOracle__factory";
